---
title: "Laboratório 07"
author: "Alessandro Silva - RA: 236928"
format: pdf
editor: visual
---

## Questão 1

```{r setup}
library(RSQLite)
```


```{r conexao}
conn <- dbConnect(SQLite(), "database.sqlite3")
```

## Questão 2

```{r q2}
professores_stat <- dbGetQuery(conn, "
  SELECT DISTINCT i.id, i.name
  FROM instructors i
  JOIN teachings t ON t.instructor_id = i.id
  JOIN sections s ON s.uuid = t.section_uuid
  JOIN course_offerings co ON co.uuid = s.course_offering_uuid
  JOIN subject_memberships sm ON sm.course_offering_uuid = co.uuid
  JOIN subjects sub ON sub.code = sm.subject_code
  WHERE sub.abbreviation = 'STAT'
")

professores_stat
nrow(professores_stat)
```

## Questão 3

```{r criar-view}
dbExecute(conn, "DROP VIEW IF EXISTS stat_grades")

dbExecute(conn, "
  CREATE TEMP VIEW stat_grades AS
  SELECT
    gd.course_offering_uuid,
    gd.section_number,
    s.uuid AS section_uuid,
    co.course_uuid,
    c.name AS course_name,
    (gd.a_count*4.0 + gd.ab_count*3.5 + gd.b_count*3.0 + gd.bc_count*2.5 +
     gd.c_count*2.0 + gd.d_count*1.0 + gd.f_count*0.0) AS points,
    (gd.a_count + gd.ab_count + gd.b_count + gd.bc_count +
     gd.c_count + gd.d_count + gd.f_count) AS n_alunos
  FROM grade_distributions gd
  JOIN sections s
    ON s.course_offering_uuid = gd.course_offering_uuid
   AND s.number = gd.section_number
  JOIN course_offerings co ON co.uuid = gd.course_offering_uuid
  JOIN courses c ON c.uuid = co.course_uuid
  JOIN subject_memberships sm ON sm.course_offering_uuid = co.uuid
  JOIN subjects sub ON sub.code = sm.subject_code
  WHERE sub.abbreviation = 'STAT'
")
```

### Questão 4

```{r prof-dificil-facil}
gpa_professor <- dbGetQuery(conn, "
  SELECT i.name,
         SUM(sg.points) * 1.0 / SUM(sg.n_alunos) AS gpa_medio,
         SUM(sg.n_alunos) AS total_alunos
  FROM stat_grades sg
  JOIN teachings t ON t.section_uuid = sg.section_uuid
  JOIN instructors i ON i.id = t.instructor_id
  GROUP BY i.id, i.name
  HAVING SUM(sg.n_alunos) > 0
  ORDER BY gpa_medio
")

head(gpa_professor, 1)
tail(gpa_professor, 1)

gpa_curso <- dbGetQuery(conn, "
  SELECT course_uuid, course_name,
         SUM(points) * 1.0 / SUM(n_alunos) AS gpa_medio,
         SUM(n_alunos) AS total_alunos
  FROM stat_grades
  GROUP BY course_uuid, course_name
  HAVING SUM(n_alunos) > 0
  ORDER BY gpa_medio
")

head(gpa_curso, 1)
tail(gpa_curso, 1)
```


```{r curso-dificil-facil}
gpa_curso <- dbGetQuery(conn, "
  SELECT course_uuid, course_name,
         SUM(points) * 1.0 / SUM(n_alunos) AS gpa_medio,
         SUM(n_alunos) AS total_alunos
  FROM stat_grades
  GROUP BY course_uuid, course_name
  HAVING SUM(n_alunos) > 0
  ORDER BY gpa_medio
")

# disciplina mais difícil = menor GPA médio
head(gpa_curso, 1)

# disciplina mais fácil = maior GPA médio
tail(gpa_curso, 1)
```

## Questão 4

```{r desconectar}
dbDisconnect(conn)
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```