---
title: "Laboratório 6"
author: "Alessandro Silva - RA:236928"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)
library(dplyr)
```

## Questão 1

```{r}
path <- getwd()
fname <- file.path(path, "disco.db")
fname
```

## Questão 2

```{r}
conn <- dbConnect(RSQLite::SQLite(), fname)
```

## Questão 3

```{r}
dbListTables(conn)
```

## Questão 4

```{r}
dbListFields(conn, "customers")
```

## Questão 5

```{r}
dbGetQuery(conn, "SELECT COUNT(*) AS total_clientes FROM customers")
```

## Questão 6

```{r}
dbGetQuery(conn, "SELECT COUNT(DISTINCT Country) AS num_paises FROM customers")
```

## Questão 7

```{r}
dbGetQuery(conn, "
  SELECT Country, COUNT(*) AS quantidade
  FROM customers
  GROUP BY Country
  ORDER BY quantidade DESC
")
```

## Questão 8

```{r}
dbGetQuery(conn, "
  SELECT Country, COUNT(*) AS quantidade
  FROM customers
  GROUP BY Country
  ORDER BY quantidade DESC
  LIMIT 5
")
```

## Questão 9

```{r}
dbGetQuery(conn, "
  SELECT DISTINCT Country
  FROM customers
  WHERE LENGTH(Country) = 6
")
```

## Questão 10

```{r}
dbGetQuery(conn, "
  SELECT DISTINCT t.Name AS musica
  FROM customers c
  INNER JOIN invoices i ON c.CustomerId = i.CustomerId
  INNER JOIN invoice_items ii ON i.InvoiceId = ii.InvoiceId
  INNER JOIN tracks t ON ii.TrackId = t.TrackId
  WHERE c.Country = 'Brazil'
")
```

## Questão 11

```{r}
dbDisconnect(conn)
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```