---
title: "ME315_LISTA02"
author: "Alessandro Silva - 236928"
format: typst
editor: visual
---

```{r}
library(DBI)
library(RSQLite)

#conexão com SQL
con <- dbConnect(SQLite(), "me315.sqlite")
```

# Questão 1

```{sql connection=con}
SELECT *
FROM PRESERVE
ORDER BY ACRES
```
# Questão 2
```{sql connection=con}
SELECT PNAME, FEE
FROM PRESERVE
WHERE STATE ="MT"
ORDER BY PNAME DESC
```

# Questão 3
```{sql connection=con}
SELECT FEE, ACRES
FROM PRESERVE
ORDER BY FEE, ACRES
```

# Questão 4
```{sql connection=con}
SELECT PNAME
FROM PRESERVE
WHERE STATE = "AZ"
ORDER BY PNO
```

# Questão 5
```{sql connection=con}
SELECT STATE, FEE, PNO
FROM PRESERVE
WHERE ACRES > 100
ORDER BY STATE DESC, FEE DESC, PNO
```

# Questão 6
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE STATE >= "M"
```

# Questão 7
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE PNAME < "TATKON"
```

# Questão 9
```{sql connection=con}
SELECT *
FROM EMPLOYEE
ORDER BY ENAME
```

# Questão 10
```{sql connection=con}
SELECT ENAME, SALARY
FROM EMPLOYEE
WHERE SALARY > 2000
ORDER BY SALARY DESC
```

# Questão 11
```{sql connection=con}
SELECT DNO, ENO, ENAME
FROM EMPLOYEE
ORDER BY DNO DESC, ENO
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

