---
title: "Lista03_ME315A"
format: pdf
editor: visual
---

# Questão 1
```{r}
library(DBI)
library(RSQLite)

#conexão com SQL
con <- dbConnect(SQLite(), "me315.sqlite")
```

```{sql connection=con}
select distinct STATE, FEE
FROM PRESERVE
```
# Questão 2
```{sql connection=con}
select distinct DNO
FROM EMPLOYEE
```
# Questão 3
```{sql connection=con}
SELECT DNO, SALARY 
FROM EMPLOYEE
```
```{sql connection=con}
SELECT DISTINCT DNO, SALARY 
FROM EMPLOYEE
```
```{sql connection=con}
SELECT DISTINCT DNO, SALARY 
FROM EMPLOYEE 
ORDER BY DNO, SALARY
```
As informações já não possuíam duplicatas, então as informações ficaram idênticas, no entanto, organizadas.

# Questão 4
```{sql connection=con}
SELECT * 
FROM PRESERVE
WHERE STATE='MT' AND ACRES < 1000
```
# Questão 5 
```{sql connection=con}
SELECT * 
FROM PRESERVE
WHERE ACRES between 1200 and 15000
```

# Questão 6
```{sql connection=con}
SELECT * 
FROM PRESERVE
where STATE='MT' AND FEE=0 
```

# Questão 7
```{sql connection=con}
SELECT * 
FROM PRESERVE
where STATE='MT' OR 'MA'
```
# Questão 8
```{sql connection=con}
SELECT * 
FROM PRESERVE
where STATE='MT' OR ACRES <1000
```

# Questão 9
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE FEE!=0
```
# Questão 10
```{sql connection=con}
SELECT PNO, PNAME
FROM PRESERVE
WHERE FEE!=3 AND FEE!=10
```
# Questão 11
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE (STATE='AZ' AND FEE=0) OR ACRES<100
```

# Questão 12
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE (ACRES<1000 AND FEE=0) OR STATE='AZ'
```

# Questão 13
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE FEE<0 OR (STATE='AZ' AND ACRES>1000)

```
# Questão 14
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE NOT (STATE = 'MT' AND (FEE = 0));
```

# Questão 15
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE STATE = 'MA' AND (ACRES > 1000 OR FEE = 0.0)
```
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE (STATE = 'MA' AND ACRES > 1000) OR (STATE = 'MA' AND FEE = 0.0)
```
São equivalentes.

# Questão 16
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE STATE = 'MA' OR (ACRES > 1000 AND FEE = 0.0)
```
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE (STATE = 'MA' OR ACRES > 1000) AND (STATE = 'MA' OR FEE = 0.0)
```
São equivalentes.

# Questão 17
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE NOT (ACRES < 50 AND STATE = 'MA')
```
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE NOT ACRES < 50 AND NOT STATE = 'MA'
```
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE ACRES >= 50 OR STATE <> 'MA'
```

Não são equivalentes.

# Questão 18
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE NOT (ACRES < 50 OR STATE = 'MA')
```

```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE NOT ACRES < 50 OR NOT STATE = 'MA'
```
```{sql connection=con}
SELECT *
FROM PRESERVE
WHERE NOT ACRES < 50 AND NOT STATE = 'MA'
```
Não são equivalentes.

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

